image:
  repository: slashmnt/krar
  pullPolicy: IfNotPresent
  tag: 2.0.0

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

resources:
  requests:
    memory: 10Mi

podAnnotations: {}
podLabels: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

nodeSelector: {}
tolerations: []
affinity: {}

roleClusterAnnotations: {}
roleClusterBindingAnnotations: {}
serviceAccountAnnotations: {}

jobs:
  - name: once-a-month
    schedule: 0 0 1 * *
    podLabels: []
    filter:
      label:
        domain: krar.slash-mnt.com
        name: rollout-policy
        policyName: "" # Overrides the job name.
      targets: []
      # - name: ""
      #   type: Deployment # or StatefulSet, DaemonSet
      #   namespace: ""
      resources: # For RBAC and pods discovery
        - deployments
        - statefulsets
        - daemonsets
      namespaces:
        all: true
        specific: []
    mode: rollout
    smartRestart: false # Ignored if mode isn't "smart".
    registry:
      mode: anonymous # anonymous, authfile, creds or config
                      # refer to  for authfile mode
      authfile: "" # Complete path to the config.json authfile
      configPath: "" # Path to the directory containing a config.json file.
      creds: ""
    extraVolumes: []
    #  - name: authfile
    #    mountPath: /
    #    readOnly: true
    #    secret:
    #      secretName: docker-authfile
    #      items:
    #        - key: config.json
    #          path: config.json
